entity_pdf.settings:
  type: config_object
  label: 'Entity PDF settings'
  mapping:
    filename:
      type: text
      label: 'Filename for generated PDF documents.'
    tempDir:
      type: string
      label: 'Path to temporary directory.'
    openInBrowser:
      type: boolean
      label: 'Open in the browser instead of downloading.'
    renderingEngine:
      type: string
      label: 'Rendering engine plugin ID.'
